apiVersion: v1
kind: Service
metadata:
  name: my-loadbalancer-service
  labels:
    app: netflix-app
spec:
  type: LoadBalancer
  selector:
    app: netflix-app
  ports:
    - protocol: TCP
      port: 80        # The port exposed by the service
      targetPort: 8080 # The port your application listens to inside the pods
